[package]
name = "Loose"
version = "1.0.0"
published-at = "0x"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# mainnet-1.3.1
rev = "a2af559f9ea21e09ca7e377e3b477fc2b5239fc7"

[dependencies.NftProtocol]
local = "../../../contracts/nft_protocol"

[addresses]
loose = "0x"
