[package]
name = "Kiosk"
version = "1.0.0"
published-at = "0x95a441d389b07437d00dd07e0b6f05f513d7659b13fd7c5d3923c7d9d847199b"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-1.0.0
rev = "ae1212baf8f0837e25926d941db3d26a61c1bea2"

[dependencies.Permissions]
local = "./../permissions"

[dependencies.Request]
local = "./../request"

[addresses]
ob_kiosk = "0x95a441d389b07437d00dd07e0b6f05f513d7659b13fd7c5d3923c7d9d847199b"
