[package]
name = "Kiosk"
version = "1.0.0"
published-at = "0xd0a449fc6b27195df90aff0076cdd84dd43f600235b23144f2422741b1bb86a8"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# devnet-1.1.0
rev = "38c31cdd0f2ae3963d1e06f00c766cd7f90a7be6"

[dependencies.Permissions]
local = "./../permissions"

[dependencies.Request]
local = "./../request"

[addresses]
ob_kiosk = "0xd0a449fc6b27195df90aff0076cdd84dd43f600235b23144f2422741b1bb86a8"
