[package]
name = "Kiosk"
version = "1.0.0"
published-at = "0x650f6faf9e5d8e4bcc1f13906317fad34996d5795fad2ba946fe6982cdc080cf"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-1.0.0
rev = "ae1212baf8f0837e25926d941db3d26a61c1bea2"

[dependencies.Permissions]
local = "./../permissions"

[dependencies.Request]
local = "./../request"

[addresses]
ob_kiosk = "0x650f6faf9e5d8e4bcc1f13906317fad34996d5795fad2ba946fe6982cdc080cf"
