name: Update Package-Registry [Mainnet]

on: workflow_dispatch

jobs:
  update-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        id: branch_name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.BRANCH_NAME }}
          path: source

      - name: Setup dependencies
        run: |
          wget -qO stoml https://github.com/freshautomations/stoml/releases/download/v0.7.1/stoml_linux_amd64
          chmod +x stoml

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update local Package Registry
        run: |
          echo "Registering under revision: ${{ github.sha }}"
          ./source/bin/register-all.sh ${{ github.repository }} ${{ github.sha }} source remote

          cp source/versions/registry-main.json registry-main.json

          if [[ -n $(git status --porcelain "source/versions/registry-main.json") ]]; then
          # File has changes, so proceed with commit and push
            continue
          else
            # File has no changes, so skip commit and push
            echo "No version upgrades exist"
            exit 1
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[skip ci] Updated Local Registry"
          committer: OriginByte <ci@originbyte.io>
          title: Updated Local Registry
          branch: update-local-registry
          path: source
      - name: Clone target repository
        run: |
          git clone git@github.com:Origin-Byte/program-registry.git program-registry

      - name: Update remote registry
        run: |
          echo "Updating Main Package Registry"
          cp registry-main.json program-registry/registry-main.json
          cd program-registry
          git add registry-main.json
          git config user.name "OriginByte"
          git config user.email "ci@originbyte.io"
          git commit -m "Update Main Registry"
          git push
